[package]
name = "ndarray-interp"
version = "0.1.0"
authors = ["Tim DuBois <tim@neophilus.net>"]

[dependencies]
ndarray = "0.11"
ndarray-parallel = "0.7"
num-traits = "0.1"

#[dev-dependencies]
#itertools = "0.7"
